[package]
name = "knock100"
version = "0.1.0"
authors = ["SATO Daisuke <densuke@st.kobedenshi.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
